language: python
python:
    - "3.6.5"
addons:
  postgresql: "9.6"

services:
    - postgres

install:
    - pip  install -r requirements.txt

before-script:
    - psql -c "DROP DATABASE IF EXISTS tototetest;" -U postgres
    - psql -c "CREATE DATABASE totoe;" -U postgres
    - python manage.py makemigrations
    - python manage.py migrate

script:
    - coverage run --omit="*tests*,*init*,*migrations*,*wsgi*,*settings*,*urls*" --source="totoe" manage.py test&&coverage report -m

after_success:
    - coveralls
